services:
  server:
    build:
      context: ./Server
      dockerfile: ./build/dockerfile
    volumes:
      - ./core/config/.env:/app/config/.env:ro
      - ./core/config/private_key.pem:/app/config/private_key.pem:ro
      - ./core/config/public_key.pem:/app/config/public_key.pem:ro
    ports:
      - "80:8080"
      - "50051:50051"
    expose:
      - "50051"
    restart: always
    networks:
      - red-principal

networks:
  red-principal:
    driver: bridge

      
