// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: user_service.proto

package user_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PrimerNombre    string                 `protobuf:"bytes,2,opt,name=primer_nombre,json=primerNombre,proto3" json:"primer_nombre,omitempty"`
	SegundoNombre   string                 `protobuf:"bytes,3,opt,name=segundo_nombre,json=segundoNombre,proto3" json:"segundo_nombre,omitempty"` // puede ser opcional
	PrimerApellido  string                 `protobuf:"bytes,4,opt,name=primer_apellido,json=primerApellido,proto3" json:"primer_apellido,omitempty"`
	SegundoApellido string                 `protobuf:"bytes,5,opt,name=segundo_apellido,json=segundoApellido,proto3" json:"segundo_apellido,omitempty"` // puede ser opcional
	Matricula       string                 `protobuf:"bytes,6,opt,name=matricula,proto3" json:"matricula,omitempty"`
	Correo          string                 `protobuf:"bytes,7,opt,name=correo,proto3" json:"correo,omitempty"`
	Contrasena      string                 `protobuf:"bytes,8,opt,name=contrasena,proto3" json:"contrasena,omitempty"` // solo usado internamente
	Rol             int32                  `protobuf:"varint,9,opt,name=rol,proto3" json:"rol,omitempty"`              // ID de rol
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_user_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetPrimerNombre() string {
	if x != nil {
		return x.PrimerNombre
	}
	return ""
}

func (x *User) GetSegundoNombre() string {
	if x != nil {
		return x.SegundoNombre
	}
	return ""
}

func (x *User) GetPrimerApellido() string {
	if x != nil {
		return x.PrimerApellido
	}
	return ""
}

func (x *User) GetSegundoApellido() string {
	if x != nil {
		return x.SegundoApellido
	}
	return ""
}

func (x *User) GetMatricula() string {
	if x != nil {
		return x.Matricula
	}
	return ""
}

func (x *User) GetCorreo() string {
	if x != nil {
		return x.Correo
	}
	return ""
}

func (x *User) GetContrasena() string {
	if x != nil {
		return x.Contrasena
	}
	return ""
}

func (x *User) GetRol() int32 {
	if x != nil {
		return x.Rol
	}
	return 0
}

type UserSanitizer struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PrimerNombre    string                 `protobuf:"bytes,2,opt,name=primer_nombre,json=primerNombre,proto3" json:"primer_nombre,omitempty"`
	SegundoNombre   string                 `protobuf:"bytes,3,opt,name=segundo_nombre,json=segundoNombre,proto3" json:"segundo_nombre,omitempty"`
	PrimerApellido  string                 `protobuf:"bytes,4,opt,name=primer_apellido,json=primerApellido,proto3" json:"primer_apellido,omitempty"`
	SegundoApellido string                 `protobuf:"bytes,5,opt,name=segundo_apellido,json=segundoApellido,proto3" json:"segundo_apellido,omitempty"`
	Matricula       string                 `protobuf:"bytes,6,opt,name=matricula,proto3" json:"matricula,omitempty"`
	Correo          string                 `protobuf:"bytes,7,opt,name=correo,proto3" json:"correo,omitempty"`
	Rol             string                 `protobuf:"bytes,8,opt,name=rol,proto3" json:"rol,omitempty"` // nombre del rol en texto
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UserSanitizer) Reset() {
	*x = UserSanitizer{}
	mi := &file_user_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSanitizer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSanitizer) ProtoMessage() {}

func (x *UserSanitizer) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSanitizer.ProtoReflect.Descriptor instead.
func (*UserSanitizer) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{1}
}

func (x *UserSanitizer) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserSanitizer) GetPrimerNombre() string {
	if x != nil {
		return x.PrimerNombre
	}
	return ""
}

func (x *UserSanitizer) GetSegundoNombre() string {
	if x != nil {
		return x.SegundoNombre
	}
	return ""
}

func (x *UserSanitizer) GetPrimerApellido() string {
	if x != nil {
		return x.PrimerApellido
	}
	return ""
}

func (x *UserSanitizer) GetSegundoApellido() string {
	if x != nil {
		return x.SegundoApellido
	}
	return ""
}

func (x *UserSanitizer) GetMatricula() string {
	if x != nil {
		return x.Matricula
	}
	return ""
}

func (x *UserSanitizer) GetCorreo() string {
	if x != nil {
		return x.Correo
	}
	return ""
}

func (x *UserSanitizer) GetRol() string {
	if x != nil {
		return x.Rol
	}
	return ""
}

// Peticiones
type UserIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIdRequest) Reset() {
	*x = UserIdRequest{}
	mi := &file_user_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIdRequest) ProtoMessage() {}

func (x *UserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIdRequest.ProtoReflect.Descriptor instead.
func (*UserIdRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{2}
}

func (x *UserIdRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UserFilterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       map[string]string      `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserFilterRequest) Reset() {
	*x = UserFilterRequest{}
	mi := &file_user_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFilterRequest) ProtoMessage() {}

func (x *UserFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFilterRequest.ProtoReflect.Descriptor instead.
func (*UserFilterRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{3}
}

func (x *UserFilterRequest) GetFilters() map[string]string {
	if x != nil {
		return x.Filters
	}
	return nil
}

type CreateUserRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PrimerNombre    string                 `protobuf:"bytes,1,opt,name=primer_nombre,json=primerNombre,proto3" json:"primer_nombre,omitempty"`
	SegundoNombre   string                 `protobuf:"bytes,2,opt,name=segundo_nombre,json=segundoNombre,proto3" json:"segundo_nombre,omitempty"`
	PrimerApellido  string                 `protobuf:"bytes,3,opt,name=primer_apellido,json=primerApellido,proto3" json:"primer_apellido,omitempty"`
	SegundoApellido string                 `protobuf:"bytes,4,opt,name=segundo_apellido,json=segundoApellido,proto3" json:"segundo_apellido,omitempty"`
	Matricula       string                 `protobuf:"bytes,5,opt,name=matricula,proto3" json:"matricula,omitempty"`
	Correo          string                 `protobuf:"bytes,6,opt,name=correo,proto3" json:"correo,omitempty"`
	Rol             int32                  `protobuf:"varint,7,opt,name=rol,proto3" json:"rol,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_user_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreateUserRequest) GetPrimerNombre() string {
	if x != nil {
		return x.PrimerNombre
	}
	return ""
}

func (x *CreateUserRequest) GetSegundoNombre() string {
	if x != nil {
		return x.SegundoNombre
	}
	return ""
}

func (x *CreateUserRequest) GetPrimerApellido() string {
	if x != nil {
		return x.PrimerApellido
	}
	return ""
}

func (x *CreateUserRequest) GetSegundoApellido() string {
	if x != nil {
		return x.SegundoApellido
	}
	return ""
}

func (x *CreateUserRequest) GetMatricula() string {
	if x != nil {
		return x.Matricula
	}
	return ""
}

func (x *CreateUserRequest) GetCorreo() string {
	if x != nil {
		return x.Correo
	}
	return ""
}

func (x *CreateUserRequest) GetRol() int32 {
	if x != nil {
		return x.Rol
	}
	return 0
}

type UpdateUserRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PrimerNombre    string                 `protobuf:"bytes,2,opt,name=primer_nombre,json=primerNombre,proto3" json:"primer_nombre,omitempty"`
	SegundoNombre   string                 `protobuf:"bytes,3,opt,name=segundo_nombre,json=segundoNombre,proto3" json:"segundo_nombre,omitempty"`
	PrimerApellido  string                 `protobuf:"bytes,4,opt,name=primer_apellido,json=primerApellido,proto3" json:"primer_apellido,omitempty"`
	SegundoApellido string                 `protobuf:"bytes,5,opt,name=segundo_apellido,json=segundoApellido,proto3" json:"segundo_apellido,omitempty"`
	Matricula       string                 `protobuf:"bytes,6,opt,name=matricula,proto3" json:"matricula,omitempty"`
	Correo          string                 `protobuf:"bytes,7,opt,name=correo,proto3" json:"correo,omitempty"`
	Rol             int32                  `protobuf:"varint,8,opt,name=rol,proto3" json:"rol,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_user_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateUserRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateUserRequest) GetPrimerNombre() string {
	if x != nil {
		return x.PrimerNombre
	}
	return ""
}

func (x *UpdateUserRequest) GetSegundoNombre() string {
	if x != nil {
		return x.SegundoNombre
	}
	return ""
}

func (x *UpdateUserRequest) GetPrimerApellido() string {
	if x != nil {
		return x.PrimerApellido
	}
	return ""
}

func (x *UpdateUserRequest) GetSegundoApellido() string {
	if x != nil {
		return x.SegundoApellido
	}
	return ""
}

func (x *UpdateUserRequest) GetMatricula() string {
	if x != nil {
		return x.Matricula
	}
	return ""
}

func (x *UpdateUserRequest) GetCorreo() string {
	if x != nil {
		return x.Correo
	}
	return ""
}

func (x *UpdateUserRequest) GetRol() int32 {
	if x != nil {
		return x.Rol
	}
	return 0
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_user_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteUserRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Respuestas
type UserListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserSanitizer       `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserListResponse) Reset() {
	*x = UserListResponse{}
	mi := &file_user_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListResponse) ProtoMessage() {}

func (x *UserListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserListResponse.ProtoReflect.Descriptor instead.
func (*UserListResponse) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{7}
}

func (x *UserListResponse) GetUsers() []*UserSanitizer {
	if x != nil {
		return x.Users
	}
	return nil
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserSanitizer         `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_user_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{8}
}

func (x *UserResponse) GetUser() *UserSanitizer {
	if x != nil {
		return x.User
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_user_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{9}
}

var File_user_service_proto protoreflect.FileDescriptor

const file_user_service_proto_rawDesc = "" +
	"\n" +
	"\x12user_service.proto\x12\fuser_service\"\x9e\x02\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12#\n" +
	"\rprimer_nombre\x18\x02 \x01(\tR\fprimerNombre\x12%\n" +
	"\x0esegundo_nombre\x18\x03 \x01(\tR\rsegundoNombre\x12'\n" +
	"\x0fprimer_apellido\x18\x04 \x01(\tR\x0eprimerApellido\x12)\n" +
	"\x10segundo_apellido\x18\x05 \x01(\tR\x0fsegundoApellido\x12\x1c\n" +
	"\tmatricula\x18\x06 \x01(\tR\tmatricula\x12\x16\n" +
	"\x06correo\x18\a \x01(\tR\x06correo\x12\x1e\n" +
	"\n" +
	"contrasena\x18\b \x01(\tR\n" +
	"contrasena\x12\x10\n" +
	"\x03rol\x18\t \x01(\x05R\x03rol\"\x87\x02\n" +
	"\rUserSanitizer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12#\n" +
	"\rprimer_nombre\x18\x02 \x01(\tR\fprimerNombre\x12%\n" +
	"\x0esegundo_nombre\x18\x03 \x01(\tR\rsegundoNombre\x12'\n" +
	"\x0fprimer_apellido\x18\x04 \x01(\tR\x0eprimerApellido\x12)\n" +
	"\x10segundo_apellido\x18\x05 \x01(\tR\x0fsegundoApellido\x12\x1c\n" +
	"\tmatricula\x18\x06 \x01(\tR\tmatricula\x12\x16\n" +
	"\x06correo\x18\a \x01(\tR\x06correo\x12\x10\n" +
	"\x03rol\x18\b \x01(\tR\x03rol\"\x1f\n" +
	"\rUserIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x97\x01\n" +
	"\x11UserFilterRequest\x12F\n" +
	"\afilters\x18\x01 \x03(\v2,.user_service.UserFilterRequest.FiltersEntryR\afilters\x1a:\n" +
	"\fFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfb\x01\n" +
	"\x11CreateUserRequest\x12#\n" +
	"\rprimer_nombre\x18\x01 \x01(\tR\fprimerNombre\x12%\n" +
	"\x0esegundo_nombre\x18\x02 \x01(\tR\rsegundoNombre\x12'\n" +
	"\x0fprimer_apellido\x18\x03 \x01(\tR\x0eprimerApellido\x12)\n" +
	"\x10segundo_apellido\x18\x04 \x01(\tR\x0fsegundoApellido\x12\x1c\n" +
	"\tmatricula\x18\x05 \x01(\tR\tmatricula\x12\x16\n" +
	"\x06correo\x18\x06 \x01(\tR\x06correo\x12\x10\n" +
	"\x03rol\x18\a \x01(\x05R\x03rol\"\x8b\x02\n" +
	"\x11UpdateUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12#\n" +
	"\rprimer_nombre\x18\x02 \x01(\tR\fprimerNombre\x12%\n" +
	"\x0esegundo_nombre\x18\x03 \x01(\tR\rsegundoNombre\x12'\n" +
	"\x0fprimer_apellido\x18\x04 \x01(\tR\x0eprimerApellido\x12)\n" +
	"\x10segundo_apellido\x18\x05 \x01(\tR\x0fsegundoApellido\x12\x1c\n" +
	"\tmatricula\x18\x06 \x01(\tR\tmatricula\x12\x16\n" +
	"\x06correo\x18\a \x01(\tR\x06correo\x12\x10\n" +
	"\x03rol\x18\b \x01(\x05R\x03rol\"#\n" +
	"\x11DeleteUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"E\n" +
	"\x10UserListResponse\x121\n" +
	"\x05users\x18\x01 \x03(\v2\x1b.user_service.UserSanitizerR\x05users\"?\n" +
	"\fUserResponse\x12/\n" +
	"\x04user\x18\x01 \x01(\v2\x1b.user_service.UserSanitizerR\x04user\"\a\n" +
	"\x05Empty2\xe8\x02\n" +
	"\vUserService\x12G\n" +
	"\x04Read\x12\x1f.user_service.UserFilterRequest\x1a\x1e.user_service.UserListResponse\x12B\n" +
	"\aReadOne\x12\x1b.user_service.UserIdRequest\x1a\x1a.user_service.UserResponse\x12E\n" +
	"\x06Insert\x12\x1f.user_service.CreateUserRequest\x1a\x1a.user_service.UserResponse\x12E\n" +
	"\x06Update\x12\x1f.user_service.UpdateUserRequest\x1a\x1a.user_service.UserResponse\x12>\n" +
	"\x06Delete\x12\x1f.user_service.DeleteUserRequest\x1a\x13.user_service.EmptyB\x1aZ\x18../services/user_serviceb\x06proto3"

var (
	file_user_service_proto_rawDescOnce sync.Once
	file_user_service_proto_rawDescData []byte
)

func file_user_service_proto_rawDescGZIP() []byte {
	file_user_service_proto_rawDescOnce.Do(func() {
		file_user_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_service_proto_rawDesc), len(file_user_service_proto_rawDesc)))
	})
	return file_user_service_proto_rawDescData
}

var file_user_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_user_service_proto_goTypes = []any{
	(*User)(nil),              // 0: user_service.User
	(*UserSanitizer)(nil),     // 1: user_service.UserSanitizer
	(*UserIdRequest)(nil),     // 2: user_service.UserIdRequest
	(*UserFilterRequest)(nil), // 3: user_service.UserFilterRequest
	(*CreateUserRequest)(nil), // 4: user_service.CreateUserRequest
	(*UpdateUserRequest)(nil), // 5: user_service.UpdateUserRequest
	(*DeleteUserRequest)(nil), // 6: user_service.DeleteUserRequest
	(*UserListResponse)(nil),  // 7: user_service.UserListResponse
	(*UserResponse)(nil),      // 8: user_service.UserResponse
	(*Empty)(nil),             // 9: user_service.Empty
	nil,                       // 10: user_service.UserFilterRequest.FiltersEntry
}
var file_user_service_proto_depIdxs = []int32{
	10, // 0: user_service.UserFilterRequest.filters:type_name -> user_service.UserFilterRequest.FiltersEntry
	1,  // 1: user_service.UserListResponse.users:type_name -> user_service.UserSanitizer
	1,  // 2: user_service.UserResponse.user:type_name -> user_service.UserSanitizer
	3,  // 3: user_service.UserService.Read:input_type -> user_service.UserFilterRequest
	2,  // 4: user_service.UserService.ReadOne:input_type -> user_service.UserIdRequest
	4,  // 5: user_service.UserService.Insert:input_type -> user_service.CreateUserRequest
	5,  // 6: user_service.UserService.Update:input_type -> user_service.UpdateUserRequest
	6,  // 7: user_service.UserService.Delete:input_type -> user_service.DeleteUserRequest
	7,  // 8: user_service.UserService.Read:output_type -> user_service.UserListResponse
	8,  // 9: user_service.UserService.ReadOne:output_type -> user_service.UserResponse
	8,  // 10: user_service.UserService.Insert:output_type -> user_service.UserResponse
	8,  // 11: user_service.UserService.Update:output_type -> user_service.UserResponse
	9,  // 12: user_service.UserService.Delete:output_type -> user_service.Empty
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_user_service_proto_init() }
func file_user_service_proto_init() {
	if File_user_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_service_proto_rawDesc), len(file_user_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_service_proto_goTypes,
		DependencyIndexes: file_user_service_proto_depIdxs,
		MessageInfos:      file_user_service_proto_msgTypes,
	}.Build()
	File_user_service_proto = out.File
	file_user_service_proto_goTypes = nil
	file_user_service_proto_depIdxs = nil
}
